### PR TITLE
Added Skript Section to the generator

### PR DESCRIPTION
**Pull request by ItsTheSky**
This small PR provides support for new Skript Sections (2.6+), as well as updated Skript dependencies (2.6-beta2 -> 2.6.1).

Tested on 2.5.3 (Still write the sections list, but empty) and, of course, 2.6.1 (write sections as normal effect)

### CODE REVIEW

**Comment by Skylyxx** [comment]
Hi, thanks for the contribution.
Could you send an example file that your version outputs ? You said that sections are written in "effects" part but as I can see in your source the sections are in a "sections" part.

**Comment by ItsTheSky** [comment]
Sure! 
Here's the 2.5.3 result file, I'm gonna send the other one at the end of the day (don't have access to my PC actually)
[DiSky.txt](https://github.com/Skylyxx/SkriptDocsGenerator/files/8304044/DiSky.txt)

**Comment by ItsTheSky** [comment]
Hey!
I'm back with the docs generated in 2.6.1:
[DiSky.txt](https://github.com/Skylyxx/SkriptDocsGenerator/files/8306460/DiSky.txt)

**Comment by Skylyxx** [comment]
As I said, you said that sections will be documented as effects:
(cf: `write sections as normal effect`) but in the output file, it's stored in a new section called "sections". Did you try import the output file on skripthub and skunity ?

**Comment by ItsTheSky** [comment]
Oh i think you misunderstood;
I was saying that sections are stored as effect, so Name, Since, Syntaxes... is exactly the same as an effect.

**Comment by Skylyxx** [comment]
So did you try the compatibility with skripthub and skunity ?

**Comment by ItsTheSky** [comment]
I did for SkriptHub, but skUnity doesn't support sections yet iirc, need deeper test for this one.

**Comment by Skylyxx** [comment]
Okay so I'll merge soon.
Thanks for your contribution

**Pull request merged**
